import {parts as teslaParts, type PartId} from './parts';

export type Vehicle = {
  category?:'road'|'formula-1'; id:string; make:string; name:string; edition:string; color:string; paint:string;
  model:string; manifest:string; image:string; creator:string; source:string;
  license:string; licenseUrl:string; parts:typeof teslaParts; illustrative:PartId[];
};

function classicParts(ferrari:boolean):typeof teslaParts {
  const source=ferrari?'https://www.ferrari.com/en-EN/auto/f40':'https://www.porsche.com/international/accessoriesandservice/classic/models/911-g/911-turbo/';
  return [
    {id:'body',name:'Body & aerodynamics',category:'Exterior',tag:'BODY',description:ferrari?'A low, angular nose, deep side intakes and a fixed rear wing define the F40. Its lightweight body encloses a two-seat cabin and a mid-mounted engine.':'Round headlamps, flared rear arches and a whale-tail spoiler give the original 930 Turbo its distinctive silhouette.',principle:'The exterior guides airflow around the cabin and toward cooling openings. The artist’s mesh divisions are not manufacturer service-part boundaries.',specs:[['Layout',ferrari?'Mid-engine coupé':'Rear-engine coupé'],['Shown here','Artist-modeled bodywork']],source},
    {id:'glass',name:'Windows & glazing',category:'Exterior',tag:'GLAZING',description:'The windshield, side windows and rear glazing enclose the cabin while providing visibility around the car.',principle:'Curved glazing follows the roof and body profile. Seals around its edges help keep weather outside the passenger compartment.',specs:[['Role','Visibility & enclosure'],['Position','Passenger compartment']],source},
    {id:'doors',name:'Doors & panels',category:'Exterior',tag:'ACCESS',description:'Two conventionally hinged doors give access to the front seats. Exterior panels, windows and interior trim form each door assembly.',principle:'The front hinges support the door while a latch holds it closed. This view separates modeled pieces; it does not simulate the hinge mechanism.',specs:[['Doors','Two'],['Motion','Front-hinged']],source},
    {id:'cabin',name:'Cockpit & interior',category:'Interior',tag:'COCKPIT',description:ferrari?'A focused two-seat cockpit places the steering wheel, instruments and manual gear selector around the driver.':'The classic 911 cockpit combines a compact driving position, a manual gear selector and a familiar bank of round instruments.',principle:'Seats, controls and trim create the driving environment. Individual pieces reflect the source artist’s model.',specs:[['Controls','Driver-focused'],['Shown here','Source-model interior']],source},
    {id:'drive',name:ferrari?'Engine & drivetrain':'Engine & exhaust',category:'Powertrain',tag:'POWERTRAIN',description:ferrari?'A twin-turbocharged V8 sits behind the cabin and drives the rear wheels through a manual transmission.':'The 930 places a turbocharged, air-cooled flat-six behind the rear axle, sending power to the rear wheels.',principle:'Exhaust gas spins a turbine connected to an intake compressor. The engine turns compressed air and fuel into mechanical power. Only geometry present in the source asset is shown.',specs:[['Engine',ferrari?'Twin-turbo V8':'Turbocharged flat-six'],['Driven wheels','Rear']],source},
    {id:'wheels',name:'Wheels & brakes',category:'Chassis',tag:'ROAD CONTACT',description:'The tires connect the car to the road. Wheel rims support the tires, while brake components help slow the rotating assemblies.',principle:'Friction between brake pads and discs converts motion into heat. Tire contact patches transmit acceleration, cornering and braking forces to the road.',specs:[['Role','Grip & braking'],['Shown here','Source-model assemblies']],source},
  ];
}

export const vehicles:Vehicle[] = [
  {id:'ferrari-f40',make:'Ferrari',name:'F40',edition:'Twin-turbo V8 · Mid-engine',color:'Red',paint:'#eb3c32',model:'/models/ferrari-f40.glb',manifest:'/models/ferrari-f40-manifest.json',image:'/cars/ferrari-f40.webp',creator:'Seatla Morake',source:'https://www.blendkit.com/asset-gallery-detail/ac7deb9f-9e90-45ec-b7d2-d390e9bcf5f1/',license:'Blendkit Royalty Free',licenseUrl:'https://www.blendkit.com/docs/licenses/',parts:classicParts(true),illustrative:[]},
  {id:'porsche-930',make:'Porsche',name:'911 Turbo',edition:'1975 · Type 930',color:'Yellow',paint:'#f2c83e',model:'/models/porsche-930.glb',manifest:'/models/porsche-930-manifest.json',image:'/cars/porsche-930.webp',creator:'Karol Miklas',source:'https://sketchfab.com/3d-models/free-1975-porsche-911-930-turbo-8568d9d14a994b9cae59499f0dbed21e',license:'CC BY 4.0',licenseUrl:'https://creativecommons.org/licenses/by/4.0/',parts:classicParts(false),illustrative:[]},
];
export function getVehicle(id:string){return vehicles.find(vehicle=>vehicle.id===id);}


// Additional licensed collection assets.
function sourceParts(ids:PartId[],source:string,racing:boolean):typeof teslaParts {
 const descriptions:Partial<Record<PartId,[string,string,string]>>={
  body:[racing?'Chassis & aerodynamics':'Bodywork & trim','Exterior',racing?'Explore the nose, wings, sidepods and chassis surfaces that define this racing car.':'Explore the body panels, lighting, grilles and exterior trim that define this car’s silhouette.'],
  glass:['Windows & glazing','Exterior','The windshield and side glazing enclose the cabin and provide visibility around the car.'],
  cabin:[racing?'Cockpit':'Cabin & controls','Interior','Explore the seats, instruments and interior trim included in the artist’s model.'],
  wheels:['Wheels & brakes','Chassis','The tires provide contact with the road. Rims support the tires, while brake components slow the rotating assemblies.'],
  drive:['Exhaust & drivetrain','Powertrain','Explore the visible powertrain and exhaust details included in this model.'],
  suspension:['Suspension','Chassis','Suspension links connect the wheels to the chassis and guide their movement.'],
  doors:['Doors & panels','Exterior','Door panels provide access to the cabin and continue the car’s exterior surfaces.'],
 };
 return ids.map(id=>{const [name,category,description]=descriptions[id]!;return {id,name,category,tag:category.toUpperCase(),description,principle:'The studio separates real geometry from the source asset. These mesh divisions are an artistic study, not a manufacturer service diagram.',specs:[['Shown here','Source-model geometry'],['View','Assembled or exploded']],source};});
}
vehicles.push(
{"id": "rolls-royce-phantom", "make": "Rolls-Royce", "name": "Phantom", "edition": "2022 \u00b7 Extended Series II", "color": "Midnight blue", "paint": "#343d51", "creator": "ig.ghazigfx", "source": "https://sketchfab.com/3d-models/2022-rolls-royce-phantom-extended-series-ii-1923bdcbc32f442e97dd49201aa2c928", "license": "CC BY 4.0", "licenseUrl": "https://creativecommons.org/licenses/by/4.0/", "model": "/models/rolls-royce-phantom.glb", "manifest": "/models/rolls-royce-phantom-manifest.json", "image": "/cars/rolls-royce-phantom.webp", "category": "road", illustrative:[],parts:sourceParts(["body", "wheels", "glass"],"https://sketchfab.com/3d-models/2022-rolls-royce-phantom-extended-series-ii-1923bdcbc32f442e97dd49201aa2c928",false)},
{"id": "aston-martin-db5", "make": "Aston Martin", "name": "DB5", "edition": "Classic grand tourer", "color": "British green", "paint": "#328a86", "creator": "AngryBearr", "source": "https://sketchfab.com/3d-models/aston-martin-db5-bf1fe23e1578417ab11db67dc89fbe32", "license": "CC BY 4.0", "licenseUrl": "https://creativecommons.org/licenses/by/4.0/", "model": "/models/aston-martin-db5.glb", "manifest": "/models/aston-martin-db5-manifest.json", "image": "/cars/aston-martin-db5.webp", "category": "road", illustrative:[],parts:sourceParts(["glass", "cabin", "body", "wheels"],"https://sketchfab.com/3d-models/aston-martin-db5-bf1fe23e1578417ab11db67dc89fbe32",false)},
{"id": "ferrari-roma", "make": "Ferrari", "name": "Roma", "edition": "Modern grand tourer", "color": "Red", "paint": "#d33b42", "creator": "zizian", "source": "https://sketchfab.com/3d-models/ferrari-roma-vr-ready-nr-130-no-for-sell-eed82330760041b7bb9583cff3e97813", "license": "CC BY 4.0", "licenseUrl": "https://creativecommons.org/licenses/by/4.0/", "model": "/models/ferrari-roma.glb", "manifest": "/models/ferrari-roma-manifest.json", "image": "/cars/ferrari-roma.webp", "category": "road", illustrative:[],parts:sourceParts(["body", "wheels", "glass", "cabin"],"https://sketchfab.com/3d-models/ferrari-roma-vr-ready-nr-130-no-for-sell-eed82330760041b7bb9583cff3e97813",false)},
{"id": "lamborghini-diablo", "make": "Lamborghini", "name": "Diablo SV", "edition": "1998 \u00b7 Low-poly study", "color": "Yellow", "paint": "#e4bc36", "creator": "anathlyst", "source": "https://sketchfab.com/3d-models/cf2efc656451443882d72418c1aa6d96", "license": "CC BY 4.0", "licenseUrl": "https://creativecommons.org/licenses/by/4.0/", "model": "/models/lamborghini-diablo.glb", "manifest": "/models/lamborghini-diablo-manifest.json", "image": "/cars/lamborghini-diablo.webp", "category": "road", illustrative:[],parts:sourceParts(["body", "wheels", "glass"],"https://sketchfab.com/3d-models/cf2efc656451443882d72418c1aa6d96",false)},
{"id": "range-rover", "make": "Land Rover", "name": "Range Rover", "edition": "Full-size luxury SUV", "color": "Silver", "paint": "#b7bdc5", "creator": "VTX", "source": "https://sketchfab.com/3d-models/range-rover-f0702fae150f4cfd98065def645edbde", "license": "CC BY-NC-SA 4.0", "licenseUrl": "https://creativecommons.org/licenses/by-nc-sa/4.0/", "model": "/models/range-rover.glb", "manifest": "/models/range-rover-manifest.json", "image": "/cars/range-rover.webp", "category": "road", illustrative:[],parts:sourceParts(["body", "wheels"],"https://sketchfab.com/3d-models/range-rover-f0702fae150f4cfd98065def645edbde",false)},
{"id":"mercedes-300sl","make":"Mercedes-Benz","name":"300 SL","edition":"1954 · Gullwing","color":"Silver","paint":"#b9c0c4","creator":"Lexyc16","source":"https://sketchfab.com/3d-models/505241c829c540a4921533000736904e","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/mercedes-300sl.glb","manifest":"/models/mercedes-300sl-manifest.json","image":"/cars/mercedes-300sl.webp","category":"road",illustrative:[],parts:sourceParts(["body","wheels","glass","cabin","drive"],"https://sketchfab.com/3d-models/505241c829c540a4921533000736904e",false)},
{"id":"mercedes-amg-one","make":"Mercedes-AMG","name":"ONE","edition":"2022 · Stylized study","color":"Silver","paint":"#6c7b85","creator":"Car Studio","source":"https://www.mercedes-amg.com/en/home/vehicles/amg-one/hypercar.html","license":"Original project asset","licenseUrl":"https://www.mercedes-amg.com/en/home/vehicles/amg-one/hypercar.html","model":"/models/mercedes-amg-one.glb","manifest":"/models/mercedes-amg-one-manifest.json","image":"/cars/mercedes-amg-one.webp","category":"road",illustrative:[],parts:sourceParts(["body","wheels","glass","cabin","drive"],"https://www.mercedes-amg.com/en/home/vehicles/amg-one/hypercar.html",false)},
{"id":"bmw-m1","make":"BMW","name":"M1","edition":"1979 · Procar","color":"Motorsport white","paint":"#e7e7e2","creator":"Todor Malakchiev","source":"https://sketchfab.com/3d-models/16e5bc3a62ab4b78a0ef95579a09a67c","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/bmw-m1.glb","manifest":"/models/bmw-m1-manifest.json","image":"/cars/bmw-m1.webp","category":"road",illustrative:[],parts:sourceParts(["body","wheels","glass","cabin","drive"],"https://sketchfab.com/3d-models/16e5bc3a62ab4b78a0ef95579a09a67c",false)},
{"id":"bmw-m3-e30","make":"BMW","name":"M3","edition":"1986 · E30","color":"Red","paint":"#c8262c","creator":"Martin Trafas","source":"https://sketchfab.com/3d-models/free-bmw-m3-e30-ac3c7013434e403e8faff87948caf422","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/bmw-m3-e30.glb","manifest":"/models/bmw-m3-e30-manifest.json","image":"/cars/bmw-m3-e30.webp","category":"road",illustrative:[],parts:sourceParts(["body","wheels","glass","cabin","drive"],"https://sketchfab.com/3d-models/free-bmw-m3-e30-ac3c7013434e403e8faff87948caf422",false)},
{"id": "f1-sf23", "make": "Scuderia Ferrari", "name": "SF-23", "edition": "2023 \u00b7 Formula 1", "color": "Racing red", "paint": "#e13637", "creator": "Redgrund", "source": "https://sketchfab.com/3d-models/scuderia-ferrari-f1-sf23-2023-ecb0f812bc454331bbe721655b0780ec", "license": "CC BY 4.0", "licenseUrl": "https://creativecommons.org/licenses/by/4.0/", "model": "/models/f1-sf23.glb", "manifest": "/models/f1-sf23-manifest.json", "image": "/cars/f1-sf23.webp", "category": "formula-1", illustrative:[],parts:sourceParts(["wheels", "body"],"https://sketchfab.com/3d-models/scuderia-ferrari-f1-sf23-2023-ecb0f812bc454331bbe721655b0780ec",true)},
{"id": "f1-amr23", "make": "Aston Martin", "name": "AMR23", "edition": "2023 \u00b7 Formula 1", "color": "Racing green", "paint": "#167b68", "creator": "Redgrund", "source": "https://sketchfab.com/3d-models/aston-martin-f1-amr23-2023-f6ba825a43b146a9b669934a4e1fd529", "license": "CC BY 4.0", "licenseUrl": "https://creativecommons.org/licenses/by/4.0/", "model": "/models/f1-amr23.glb", "manifest": "/models/f1-amr23-manifest.json", "image": "/cars/f1-amr23.webp", "category": "formula-1", illustrative:[],parts:sourceParts(["body", "wheels"],"https://sketchfab.com/3d-models/aston-martin-f1-amr23-2023-f6ba825a43b146a9b669934a4e1fd529",true)},
{"id":"f1-mercedes-w14","make":"Mercedes-AMG","name":"W14","edition":"2023 · Formula 1","color":"Black","paint":"#141719","creator":"3dblender_1","source":"https://sketchfab.com/3d-models/mercedes-f1-w14-free-26fda66f3e8a48d5a636056f8a64e299","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/f1-mercedes-w14.glb","manifest":"/models/f1-mercedes-w14-manifest.json","image":"/cars/f1-mercedes-w14.webp","category":"formula-1",illustrative:[],parts:sourceParts(["body","wheels","cabin","suspension"],"https://sketchfab.com/3d-models/mercedes-f1-w14-free-26fda66f3e8a48d5a636056f8a64e299",true)},
{"id":"f1-mclaren-mp45","make":"McLaren-Honda","name":"MP4/5","edition":"1989 · Formula 1","color":"Red and white","paint":"#df302f","creator":"vecarz","source":"https://sketchfab.com/3d-models/mclaren-mp45-wwwvecarzcom-b0db423a98584469a73ad9b5df2ab969","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/f1-mclaren-mp45.glb","manifest":"/models/f1-mclaren-mp45-manifest.json","image":"/cars/f1-mclaren-mp45.webp","category":"formula-1",illustrative:[],parts:sourceParts(["body","wheels","cabin","suspension"],"https://sketchfab.com/3d-models/mclaren-mp45-wwwvecarzcom-b0db423a98584469a73ad9b5df2ab969",true)},
{id:'model-x',make:'Tesla',name:'Model X',edition:'Electric · Pre-refresh',color:'Steel blue',paint:'#8aa6bd',model:'/models/model-x.glb',manifest:'/models/model-x-manifest.json',image:'/cars/model-x.webp',creator:'cgi Moon',source:'https://www.blendkit.com/asset-gallery-detail/983e8f94-5a56-44a4-94d9-eed5e4cdcd6c/',license:'Blendkit Royalty Free',licenseUrl:'https://www.blendkit.com/docs/licenses/',parts:teslaParts,illustrative:['battery','drive','suspension']}
);
