import {parts as teslaParts, type PartId} from './parts';

export type Vehicle = {
  category?:'road'|'formula-1'; id:string; make:string; name:string; edition:string; color:string; paint:string;
  model:string; manifest:string; image:string; creator:string; source:string;
  license:string; licenseUrl:string; parts:typeof teslaParts; illustrative:PartId[];
};

function classicParts(ferrari:boolean):typeof teslaParts {
  const source=ferrari?'https://www.ferrari.com/en-EN/auto/f40':'https://www.porsche.com/international/accessoriesandservice/classic/models/911-g/911-turbo/';
  return [
    {id:'body',name:'Body & aerodynamics',category:'Exterior',tag:'BODY',description:ferrari?'A low, angular nose, deep side intakes and a fixed rear wing define the F40. Its lightweight body encloses a two-seat cabin and a mid-mounted engine.':'Round headlamps, flared rear arches and a whale-tail spoiler give the original 930 Turbo its distinctive silhouette.',principle:'The exterior guides airflow around the cabin and toward cooling openings. The artist’s mesh divisions are not manufacturer service-part boundaries.',specs:[['Layout',ferrari?'Mid-engine coupé':'Rear-engine coupé'],['Shown here','Artist-modeled bodywork']],source},
    {id:'glass',name:'Windows & glazing',category:'Exterior',tag:'GLAZING',description:'The windshield, side windows and rear glazing enclose the cabin while providing visibility around the car.',principle:'Curved glazing follows the roof and body profile. Seals around its edges help keep weather outside the passenger compartment.',specs:[['Role','Visibility & enclosure'],['Position','Passenger compartment']],source},
    {id:'doors',name:'Doors & panels',category:'Exterior',tag:'ACCESS',description:'Two conventionally hinged doors give access to the front seats. Exterior panels, windows and interior trim form each door assembly.',principle:'The front hinges support the door while a latch holds it closed. This view separates modeled pieces; it does not simulate the hinge mechanism.',specs:[['Doors','Two'],['Motion','Front-hinged']],source},
    {id:'cabin',name:'Cockpit & interior',category:'Interior',tag:'COCKPIT',description:ferrari?'A focused two-seat cockpit places the steering wheel, instruments and manual gear selector around the driver.':'The classic 911 cockpit combines a compact driving position, a manual gear selector and a familiar bank of round instruments.',principle:'Seats, controls and trim create the driving environment. Individual pieces reflect the source artist’s model.',specs:[['Controls','Driver-focused'],['Shown here','Source-model interior']],source},
    {id:'drive',name:ferrari?'Engine & drivetrain':'Engine & exhaust',category:'Powertrain',tag:'POWERTRAIN',description:ferrari?'A twin-turbocharged V8 sits behind the cabin and drives the rear wheels through a manual transmission.':'The 930 places a turbocharged, air-cooled flat-six behind the rear axle, sending power to the rear wheels.',principle:'Exhaust gas spins a turbine connected to an intake compressor. The engine turns compressed air and fuel into mechanical power. Only geometry present in the source asset is shown.',specs:[['Engine',ferrari?'Twin-turbo V8':'Turbocharged flat-six'],['Driven wheels','Rear']],source},
    {id:'wheels',name:'Wheels & brakes',category:'Chassis',tag:'ROAD CONTACT',description:'The tires connect the car to the road. Wheel rims support the tires, while brake components help slow the rotating assemblies.',principle:'Friction between brake pads and discs converts motion into heat. Tire contact patches transmit acceleration, cornering and braking forces to the road.',specs:[['Role','Grip & braking'],['Shown here','Source-model assemblies']],source},
  ];
}

export const vehicles:Vehicle[] = [
  {id:'ferrari-f40',make:'Ferrari',name:'F40',edition:'Twin-turbo V8 · Mid-engine',color:'Red',paint:'#eb3c32',model:'/models/ferrari-f40.glb',manifest:'/models/ferrari-f40-manifest.json',image:'/cars/ferrari-f40.webp',creator:'Seatla Morake',source:'https://www.blendkit.com/asset-gallery-detail/ac7deb9f-9e90-45ec-b7d2-d390e9bcf5f1/',license:'Blendkit Royalty Free',licenseUrl:'https://www.blendkit.com/docs/licenses/',parts:classicParts(true),illustrative:[]},
  {id:'porsche-930',make:'Porsche',name:'911 Turbo',edition:'1975 · Type 930',color:'Yellow',paint:'#f2c83e',model:'/models/porsche-930.glb',manifest:'/models/porsche-930-manifest.json',image:'/cars/porsche-930.webp',creator:'Karol Miklas',source:'https://sketchfab.com/3d-models/free-1975-porsche-911-930-turbo-8568d9d14a994b9cae59499f0dbed21e',license:'CC BY 4.0',licenseUrl:'https://creativecommons.org/licenses/by/4.0/',parts:classicParts(false),illustrative:[]},
];
export function getVehicle(id:string){return vehicles.find(vehicle=>vehicle.id===id);}


// Additional licensed collection assets.
function sourceParts(ids:PartId[],source:string,racing:boolean):typeof teslaParts {
 const descriptions:Partial<Record<PartId,[string,string,string]>>={
  body:[racing?'Chassis & aerodynamics':'Bodywork & trim','Exterior',racing?'Explore the nose, wings, sidepods and chassis surfaces that define this racing car.':'Explore the body panels, lighting, grilles and exterior trim that define this car’s silhouette.'],
  glass:['Windows & glazing','Exterior','The windshield and side glazing enclose the cabin and provide visibility around the car.'],
  cabin:[racing?'Cockpit':'Cabin & controls','Interior','Explore the seats, instruments and interior trim included in the artist’s model.'],
  wheels:['Wheels & brakes','Chassis','The tires provide contact with the road. Rims support the tires, while brake components slow the rotating assemblies.'],
  drive:['Exhaust & drivetrain','Powertrain','Explore the visible powertrain and exhaust details included in this model.'],
  suspension:['Suspension','Chassis','Suspension links connect the wheels to the chassis and guide their movement.'],
  doors:['Doors & panels','Exterior','Door panels provide access to the cabin and continue the car’s exterior surfaces.'],
 };
 return ids.map(id=>{const [name,category,description]=descriptions[id]!;return {id,name,category,tag:category.toUpperCase(),description,principle:'The studio separates real geometry from the source asset. These mesh divisions are an artistic study, not a manufacturer service diagram.',specs:[['Shown here','Source-model geometry'],['View','Assembled or exploded']],source};});
}
vehicles.push(
{"id": "rolls-royce-phantom", "make": "Rolls-Royce", "name": "Phantom", "edition": "2022 \u00b7 Extended Series II", "color": "Midnight blue", "paint": "#343d51", "creator": "ig.ghazigfx", "source": "https://sketchfab.com/3d-models/2022-rolls-royce-phantom-extended-series-ii-1923bdcbc32f442e97dd49201aa2c928", "license": "CC BY 4.0", "licenseUrl": "https://creativecommons.org/licenses/by/4.0/", "model": "/models/rolls-royce-phantom.glb", "manifest": "/models/rolls-royce-phantom-manifest.json", "image": "/cars/rolls-royce-phantom.webp", "category": "road", illustrative:[],parts:sourceParts(["body", "wheels", "glass"],"https://sketchfab.com/3d-models/2022-rolls-royce-phantom-extended-series-ii-1923bdcbc32f442e97dd49201aa2c928",false)},
{"id": "aston-martin-db5", "make": "Aston Martin", "name": "DB5", "edition": "Classic grand tourer", "color": "Silver birch", "paint": "#c2c4bf", "creator": "AngryBearr", "source": "https://sketchfab.com/3d-models/aston-martin-db5-bf1fe23e1578417ab11db67dc89fbe32", "license": "CC BY 4.0", "licenseUrl": "https://creativecommons.org/licenses/by/4.0/", "model": "/models/aston-martin-db5.glb", "manifest": "/models/aston-martin-db5-manifest.json", "image": "/cars/aston-martin-db5.webp", "category": "road", illustrative:[],parts:sourceParts(["glass", "cabin", "body", "wheels"],"https://sketchfab.com/3d-models/aston-martin-db5-bf1fe23e1578417ab11db67dc89fbe32",false)},
{"id": "ferrari-roma", "make": "Ferrari", "name": "Roma", "edition": "Modern grand tourer", "color": "Red", "paint": "#d33b42", "creator": "zizian", "source": "https://sketchfab.com/3d-models/ferrari-roma-vr-ready-nr-130-no-for-sell-eed82330760041b7bb9583cff3e97813", "license": "CC BY 4.0", "licenseUrl": "https://creativecommons.org/licenses/by/4.0/", "model": "/models/ferrari-roma.glb", "manifest": "/models/ferrari-roma-manifest.json", "image": "/cars/ferrari-roma.webp", "category": "road", illustrative:[],parts:sourceParts(["body", "wheels", "glass", "cabin"],"https://sketchfab.com/3d-models/ferrari-roma-vr-ready-nr-130-no-for-sell-eed82330760041b7bb9583cff3e97813",false)},
{"id": "lamborghini-diablo", "make": "Lamborghini", "name": "Diablo SV", "edition": "1998 \u00b7 Low-poly study", "color": "Yellow", "paint": "#e4bc36", "creator": "anathlyst", "source": "https://sketchfab.com/3d-models/cf2efc656451443882d72418c1aa6d96", "license": "CC BY 4.0", "licenseUrl": "https://creativecommons.org/licenses/by/4.0/", "model": "/models/lamborghini-diablo.glb", "manifest": "/models/lamborghini-diablo-manifest.json", "image": "/cars/lamborghini-diablo.webp", "category": "road", illustrative:[],parts:sourceParts(["body", "wheels", "glass"],"https://sketchfab.com/3d-models/cf2efc656451443882d72418c1aa6d96",false)},
{"id":"lamborghini-countach","make":"Lamborghini","name":"Countach","edition":"1982 · LP500S","color":"Electric blue","paint":"#0529eb","creator":"SDC PERFORMANCE™️","source":"https://sketchfab.com/3d-models/32e9ee8d129e4c2992e1753b4fc3094c","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/lamborghini-countach.glb","manifest":"/models/lamborghini-countach-manifest.json","image":"/cars/lamborghini-countach.webp","category":"road",illustrative:[],parts:sourceParts(["body","wheels","glass","cabin","drive"],"https://sketchfab.com/3d-models/32e9ee8d129e4c2992e1753b4fc3094c",false)},
{"id": "range-rover", "make": "Land Rover", "name": "Range Rover", "edition": "Full-size luxury SUV", "color": "Silver", "paint": "#b7bdc5", "creator": "VTX", "source": "https://sketchfab.com/3d-models/range-rover-f0702fae150f4cfd98065def645edbde", "license": "CC BY-NC-SA 4.0", "licenseUrl": "https://creativecommons.org/licenses/by-nc-sa/4.0/", "model": "/models/range-rover.glb", "manifest": "/models/range-rover-manifest.json", "image": "/cars/range-rover.webp", "category": "road", illustrative:[],parts:sourceParts(["body", "wheels"],"https://sketchfab.com/3d-models/range-rover-f0702fae150f4cfd98065def645edbde",false)},
{"id":"mercedes-300sl","make":"Mercedes-Benz","name":"300 SL","edition":"1954 · Gullwing","color":"Silver","paint":"#b9c0c4","creator":"Lexyc16","source":"https://sketchfab.com/3d-models/505241c829c540a4921533000736904e","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/mercedes-300sl.glb","manifest":"/models/mercedes-300sl-manifest.json","image":"/cars/mercedes-300sl.webp","category":"road",illustrative:[],parts:sourceParts(["body","wheels","glass","cabin","drive"],"https://sketchfab.com/3d-models/505241c829c540a4921533000736904e",false)},
{"id":"mercedes-amg-one","make":"Mercedes-AMG","name":"ONE","edition":"2022 · F1-derived hypercar","color":"Silver","paint":"#7d858b","creator":"srush651","source":"https://sketchfab.com/3d-models/15690215e244466f9c4ae0f3acc20020","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/mercedes-amg-one.glb","manifest":"/models/mercedes-amg-one-manifest.json","image":"/cars/mercedes-amg-one.webp","category":"road",illustrative:[],parts:sourceParts(["body","wheels","glass","cabin","drive"],"https://sketchfab.com/3d-models/15690215e244466f9c4ae0f3acc20020",false)},
{"id":"bmw-m1","make":"BMW","name":"M1","edition":"1979 · Procar","color":"Motorsport white","paint":"#e7e7e2","creator":"Todor Malakchiev","source":"https://sketchfab.com/3d-models/16e5bc3a62ab4b78a0ef95579a09a67c","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/bmw-m1.glb","manifest":"/models/bmw-m1-manifest.json","image":"/cars/bmw-m1.webp","category":"road",illustrative:[],parts:sourceParts(["body","wheels","glass","cabin","drive"],"https://sketchfab.com/3d-models/16e5bc3a62ab4b78a0ef95579a09a67c",false)},
{"id":"bmw-m3-e30","make":"BMW","name":"M3","edition":"1986 · E30","color":"Red","paint":"#c8262c","creator":"Martin Trafas","source":"https://sketchfab.com/3d-models/free-bmw-m3-e30-ac3c7013434e403e8faff87948caf422","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/bmw-m3-e30.glb","manifest":"/models/bmw-m3-e30-manifest.json","image":"/cars/bmw-m3-e30.webp","category":"road",illustrative:[],parts:sourceParts(["body","wheels","glass","cabin","drive"],"https://sketchfab.com/3d-models/free-bmw-m3-e30-ac3c7013434e403e8faff87948caf422",false)},
{"id":"toyota-supra-mk4","make":"Toyota","name":"Supra Mk4","edition":"1993 · A80","color":"Red","paint":"#c8342a","creator":"Lexyc16","source":"https://sketchfab.com/3d-models/toyota-supra-a80-1993-dd897d7823784bc5893c183c1328e8cb","license":"CC BY-NC 4.0","licenseUrl":"https://creativecommons.org/licenses/by-nc/4.0/","model":"/models/toyota-supra-mk4.glb","manifest":"/models/toyota-supra-mk4-manifest.json","image":"/cars/toyota-supra-mk4.webp","category":"road",illustrative:[],parts:sourceParts(["body","wheels","glass","cabin"],"https://sketchfab.com/3d-models/toyota-supra-a80-1993-dd897d7823784bc5893c183c1328e8cb",false)},
{"id":"nissan-skyline-r34","make":"Nissan","name":"Skyline GT-R","edition":"1999 · R34","color":"Bayside blue","paint":"#266fd0","creator":"Lexyc16","source":"https://sketchfab.com/3d-models/nissan-skyline-r34-gt-r-ff8fb2251dfa4bb9979e7022c5a6666c","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/nissan-skyline-r34.glb","manifest":"/models/nissan-skyline-r34-manifest.json","image":"/cars/nissan-skyline-r34.webp","category":"road",illustrative:[],parts:sourceParts(["body","wheels","glass","cabin","drive"],"https://sketchfab.com/3d-models/nissan-skyline-r34-gt-r-ff8fb2251dfa4bb9979e7022c5a6666c",false)},
{"id":"audi-quattro","make":"Audi","name":"Quattro S1","edition":"1985 · Group B","color":"White and yellow","paint":"#d8c675","creator":"TonyWony","source":"https://sketchfab.com/3d-models/audi-quattro-s1-402697365eaa41a68a543b71d0e0bfa8","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/audi-quattro.glb","manifest":"/models/audi-quattro-manifest.json","image":"/cars/audi-quattro.webp","category":"road",illustrative:[],parts:sourceParts(["body","wheels","glass","cabin","drive"],"https://sketchfab.com/3d-models/audi-quattro-s1-402697365eaa41a68a543b71d0e0bfa8",false)},
{"id":"ferrari-250-gto","make":"Ferrari","name":"250 GTO","edition":"1962 · Low-poly study","color":"Red","paint":"#c0342e","creator":"Dave Love SketchFab","source":"https://sketchfab.com/3d-models/1962-ferrari-250-gto-b12954e759df43e882a0136c1403a800","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/ferrari-250-gto.glb","manifest":"/models/ferrari-250-gto-manifest.json","image":"/cars/ferrari-250-gto.webp","category":"road",illustrative:[],parts:sourceParts(["body","wheels"],"https://sketchfab.com/3d-models/1962-ferrari-250-gto-b12954e759df43e882a0136c1403a800",false)},
{"id":"ferrari-laferrari","make":"Ferrari","name":"LaFerrari","edition":"2013 · Hybrid hypercar","color":"Red","paint":"#c0342e","creator":"XENVOR creations","source":"https://sketchfab.com/3d-models/2013-ferrari-laferrari-f75b682bb0de4a14b3b6c1f52862ca48","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/ferrari-laferrari.glb","manifest":"/models/ferrari-laferrari-manifest.json","image":"/cars/ferrari-laferrari.webp","category":"road",illustrative:[],parts:sourceParts(["body","wheels","cabin"],"https://sketchfab.com/3d-models/2013-ferrari-laferrari-f75b682bb0de4a14b3b6c1f52862ca48",false)},
{"id":"porsche-918-spyder","make":"Porsche","name":"918 Spyder","edition":"2015 · Hybrid hypercar","color":"Red","paint":"#c0342e","creator":"Black Snow","source":"https://sketchfab.com/3d-models/porsche-918-free-ec8eebcdbf534bbba151375b9992f6d7","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/porsche-918-spyder.glb","manifest":"/models/porsche-918-spyder-manifest.json","image":"/cars/porsche-918-spyder.webp","category":"road",illustrative:[],parts:sourceParts(["body","wheels","cabin"],"https://sketchfab.com/3d-models/porsche-918-free-ec8eebcdbf534bbba151375b9992f6d7",false)},
{"id":"porsche-959","make":"Porsche","name":"959","edition":"1987 · Group B homologation","color":"Red","paint":"#c1352c","creator":"valvetin","source":"https://sketchfab.com/3d-models/1987-porsche-959-678ed0b096bd4b99839888eef6075666","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/porsche-959.glb","manifest":"/models/porsche-959-manifest.json","image":"/cars/porsche-959.webp","category":"road",illustrative:[],parts:sourceParts(["body","wheels","glass","cabin"],"https://sketchfab.com/3d-models/1987-porsche-959-678ed0b096bd4b99839888eef6075666",false)},
{"id":"lamborghini-urus","make":"Lamborghini","name":"Urus","edition":"Widebody build","color":"Black","paint":"#0d0e10","creator":"SDC PERFORMANCE™️","source":"https://sketchfab.com/3d-models/urus-absoluttm-914bbca2f7f54783a00062a695bae0ea","license":"CC BY-NC 4.0","licenseUrl":"https://creativecommons.org/licenses/by-nc/4.0/","model":"/models/lamborghini-urus.glb","manifest":"/models/lamborghini-urus-manifest.json","image":"/cars/lamborghini-urus.webp","category":"road",illustrative:[],parts:sourceParts(["body","wheels","glass"],"https://sketchfab.com/3d-models/urus-absoluttm-914bbca2f7f54783a00062a695bae0ea",false)},
{"id":"citroen-2cv","make":"Citroën","name":"2CV","edition":"1986 · Charleston","color":"Red and black","paint":"#8a2620","creator":"MaximePages","source":"https://sketchfab.com/3d-models/free-2cv-charleston-1986-abdb2d11268b405c90b117e0992693ee","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/citroen-2cv.glb","manifest":"/models/citroen-2cv-manifest.json","image":"/cars/citroen-2cv.webp","category":"road",illustrative:[],parts:sourceParts(["body","wheels","glass","cabin"],"https://sketchfab.com/3d-models/free-2cv-charleston-1986-abdb2d11268b405c90b117e0992693ee",false)},
{"id":"vw-beetle","make":"Volkswagen","name":"Beetle","edition":"1938 · KdF-Wagen","color":"Black","paint":"#1a1a1c","creator":"Libau Media","source":"https://sketchfab.com/3d-models/kdf-typ-38-7a246b187ad84b9583548b60a4348ea4","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/vw-beetle.glb","manifest":"/models/vw-beetle-manifest.json","image":"/cars/vw-beetle.webp","category":"road",illustrative:[],parts:sourceParts(["body","wheels","glass"],"https://sketchfab.com/3d-models/kdf-typ-38-7a246b187ad84b9583548b60a4348ea4",false)},
{"id":"mini-cooper","make":"Austin","name":"Mini Cooper S","edition":"Classic · Mk1","color":"Olive and white","paint":"#a9a233","creator":"Configcars","source":"https://sketchfab.com/3d-models/morris-cooper-austin-mini-b598ffa068a64e31aaf3dfa83828b8be","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/mini-cooper.glb","manifest":"/models/mini-cooper-manifest.json","image":"/cars/mini-cooper.webp","category":"road",illustrative:[],parts:sourceParts(["body","wheels"],"https://sketchfab.com/3d-models/morris-cooper-austin-mini-b598ffa068a64e31aaf3dfa83828b8be",false)},
{"id":"honda-nsx","make":"Honda","name":"NSX","edition":"1990 · NA1","color":"White","paint":"#e8e9ea","creator":"lilModels","source":"https://sketchfab.com/3d-models/1990-honda-nsx-b9c541ef47004870868bb3a2f767b85d","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/honda-nsx.glb","manifest":"/models/honda-nsx-manifest.json","image":"/cars/honda-nsx.webp","category":"road",illustrative:[],parts:sourceParts(["body","wheels"],"https://sketchfab.com/3d-models/1990-honda-nsx-b9c541ef47004870868bb3a2f767b85d",false)},
{"id":"lancia-delta","make":"Lancia","name":"Delta HF Integrale","edition":"Evo 2 · Group A rally","color":"Silver","paint":"#b8babc","creator":"TARANTULA","source":"https://sketchfab.com/3d-models/free-lancia-delta-hf-integrale-evo-2-85614131e0dc4613a948472aaa935fc7","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/lancia-delta.glb","manifest":"/models/lancia-delta-manifest.json","image":"/cars/lancia-delta.webp","category":"road",illustrative:[],parts:sourceParts(["body","wheels","glass","drive"],"https://sketchfab.com/3d-models/free-lancia-delta-hf-integrale-evo-2-85614131e0dc4613a948472aaa935fc7",false)},
{"id":"datsun-240z","make":"Datsun","name":"240Z","edition":"Rally-mod build","color":"Red","paint":"#c0342e","creator":"Mikhail_Zelenov","source":"https://sketchfab.com/3d-models/nissan-datsun-240z-25200998b5e64c278aa45606fc978eaf","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/datsun-240z.glb","manifest":"/models/datsun-240z-manifest.json","image":"/cars/datsun-240z.webp","category":"road",illustrative:[],parts:sourceParts(["body","wheels"],"https://sketchfab.com/3d-models/nissan-datsun-240z-25200998b5e64c278aa45606fc978eaf",false)},
{"id":"toyota-2000gt","make":"Toyota","name":"2000GT","edition":"1967 · Grand tourer","color":"Gold","paint":"#c9a961","creator":"AudreyGroneck","source":"https://sketchfab.com/3d-models/toyota-2000gt-3e6a48df80e242fcb9ff8d07c2ac86fa","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/toyota-2000gt.glb","manifest":"/models/toyota-2000gt-manifest.json","image":"/cars/toyota-2000gt.webp","category":"road",illustrative:[],parts:sourceParts(["body","wheels","glass","drive"],"https://sketchfab.com/3d-models/toyota-2000gt-3e6a48df80e242fcb9ff8d07c2ac86fa",false)},
{"id":"ferrari-testarossa","make":"Ferrari","name":"Testarossa","edition":"1984 · Flat-12","color":"Red","paint":"#c8272c","creator":"kekomag","source":"https://sketchfab.com/3d-models/ferrari-testarossa-84-low-poly-1786b089bfbb40ea9ecd9dc4f4e73127","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/ferrari-testarossa.glb","manifest":"/models/ferrari-testarossa-manifest.json","image":"/cars/ferrari-testarossa.webp","category":"road",illustrative:[],parts:sourceParts(["body","wheels","glass","cabin"],"https://sketchfab.com/3d-models/ferrari-testarossa-84-low-poly-1786b089bfbb40ea9ecd9dc4f4e73127",false)},
{"id":"lamborghini-miura","make":"Lamborghini","name":"Miura","edition":"1969 · P400","color":"Maroon","paint":"#4a0f16","creator":"elenstesh","source":"https://sketchfab.com/3d-models/lamborghini-miura-9b35bbed179c4c32b28f442e3da0262b","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/lamborghini-miura.glb","manifest":"/models/lamborghini-miura-manifest.json","image":"/cars/lamborghini-miura.webp","category":"road",illustrative:[],parts:sourceParts(["body","wheels"],"https://sketchfab.com/3d-models/lamborghini-miura-9b35bbed179c4c32b28f442e3da0262b",false)},
{"id":"corvette-c2","make":"Chevrolet","name":"Corvette Stingray","edition":"1963 · C2","color":"Red","paint":"#a12228","creator":"Kryox Shade","source":"https://sketchfab.com/3d-models/1963-chevy-corvette-c2-stingray-11b73ee6e15445f6bd488d6ffc2b82a8","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/corvette-c2.glb","manifest":"/models/corvette-c2-manifest.json","image":"/cars/corvette-c2.webp","category":"road",illustrative:[],parts:sourceParts(["body","wheels","glass","cabin"],"https://sketchfab.com/3d-models/1963-chevy-corvette-c2-stingray-11b73ee6e15445f6bd488d6ffc2b82a8",false)},
{"id":"shelby-cobra","make":"Shelby","name":"Cobra 427","edition":"1966 · Roadster","color":"Blue","paint":"#1f3f7a","creator":"DRIVER-FIRE","source":"https://sketchfab.com/3d-models/shelby-cobra-427-944d9d164d1540ffad3079cf0eca9886","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/shelby-cobra.glb","manifest":"/models/shelby-cobra-manifest.json","image":"/cars/shelby-cobra.webp","category":"road",illustrative:[],parts:sourceParts(["body","wheels","cabin","suspension","drive"],"https://sketchfab.com/3d-models/shelby-cobra-427-944d9d164d1540ffad3079cf0eca9886",false)},
{"id":"ford-gt40","make":"Ford","name":"GT40","edition":"Restomod build","color":"Blue","paint":"#5fa9d6","creator":"VTX","source":"https://sketchfab.com/3d-models/ruffian-gt40-a3cd7eb801cb462c859c403890c3b0da","license":"CC BY-NC-SA 4.0","licenseUrl":"https://creativecommons.org/licenses/by-nc-sa/4.0/","model":"/models/ford-gt40.glb","manifest":"/models/ford-gt40-manifest.json","image":"/cars/ford-gt40.webp","category":"road",illustrative:[],parts:sourceParts(["body","wheels","cabin"],"https://sketchfab.com/3d-models/ruffian-gt40-a3cd7eb801cb462c859c403890c3b0da",false)},
{"id":"bmw-m4","make":"BMW","name":"M4","edition":"2021 · Competition","color":"Yellow","paint":"#c9c34a","creator":"Sloftm_Carz","source":"https://sketchfab.com/3d-models/bmw-m4-g82-coupe-free-high-detail-8704e302e4214c849bc607edb294be8a","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/bmw-m4.glb","manifest":"/models/bmw-m4-manifest.json","image":"/cars/bmw-m4.webp","category":"road",illustrative:[],parts:sourceParts(["body","wheels","glass"],"https://sketchfab.com/3d-models/bmw-m4-g82-coupe-free-high-detail-8704e302e4214c849bc607edb294be8a",false)},
{"id":"mercedes-sclass","make":"Mercedes-Benz","name":"S-Class","edition":"2023 · Brabus 850","color":"Black","paint":"#0c0c0e","creator":"Black Snow","source":"https://sketchfab.com/3d-models/mersedes-benz-s-class-w223-brabus-850-297e1da45b874276aae24c4a8ec10982","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/mercedes-sclass.glb","manifest":"/models/mercedes-sclass-manifest.json","image":"/cars/mercedes-sclass.webp","category":"road",illustrative:[],parts:sourceParts(["body","wheels","cabin"],"https://sketchfab.com/3d-models/mersedes-benz-s-class-w223-brabus-850-297e1da45b874276aae24c4a8ec10982",false)},
{"id":"bmw-i8","make":"BMW","name":"i8","edition":"2015 · Hybrid coupé","color":"White","paint":"#e6e8ea","creator":"iSteven","source":"https://sketchfab.com/3d-models/bmw-i8-4b143b95aec045bf8912d99662f8d580","license":"CC BY-NC 4.0","licenseUrl":"https://creativecommons.org/licenses/by-nc/4.0/","model":"/models/bmw-i8.glb","manifest":"/models/bmw-i8-manifest.json","image":"/cars/bmw-i8.webp","category":"road",illustrative:[],parts:sourceParts(["body","wheels","glass"],"https://sketchfab.com/3d-models/bmw-i8-4b143b95aec045bf8912d99662f8d580",false)},
{"id":"mercedes-amg-gt","make":"Mercedes-AMG","name":"GT","edition":"2016 · Coupé","color":"Silver","paint":"#c7c9ca","creator":"jseopd9","source":"https://sketchfab.com/3d-models/merecedes-amg-gt-b9e066d791494fb2b62cd6c99f389294","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/mercedes-amg-gt.glb","manifest":"/models/mercedes-amg-gt-manifest.json","image":"/cars/mercedes-amg-gt.webp","category":"road",illustrative:[],parts:sourceParts(["body","wheels","glass"],"https://sketchfab.com/3d-models/merecedes-amg-gt-b9e066d791494fb2b62cd6c99f389294",false)},
{"id":"bugatti-atlantic","make":"Bugatti","name":"Type 57SC Atlantic","edition":"1936 · Vintage","color":"Blue","paint":"#8fbfd6","creator":"Res1n","source":"https://sketchfab.com/3d-models/1936-bugatti-type-57sc-atlantic-4d40726e8183405188b333189e235f3d","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/bugatti-atlantic.glb","manifest":"/models/bugatti-atlantic-manifest.json","image":"/cars/bugatti-atlantic.webp","category":"road",illustrative:[],parts:sourceParts(["body","wheels","glass","cabin"],"https://sketchfab.com/3d-models/1936-bugatti-type-57sc-atlantic-4d40726e8183405188b333189e235f3d",false)},
{"id":"ford-model-t","make":"Ford","name":"Model T","edition":"1925 · Vintage","color":"Black","paint":"#17171a","creator":"Libau Media","source":"https://sketchfab.com/3d-models/ford-model-t-v2-downloadable-028ff3c03a284216801eb05623c5b2a3","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/ford-model-t.glb","manifest":"/models/ford-model-t-manifest.json","image":"/cars/ford-model-t.webp","category":"road",illustrative:[],parts:sourceParts(["body","wheels","glass","cabin"],"https://sketchfab.com/3d-models/ford-model-t-v2-downloadable-028ff3c03a284216801eb05623c5b2a3",false)},
{"id":"audi-r8","make":"Audi","name":"R8","edition":"Widebody build","color":"Gold","paint":"#c17d40","creator":"wallon","source":"https://sketchfab.com/3d-models/audi-r8-e17e438f076f4427a58d93aa779edaed","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/audi-r8.glb","manifest":"/models/audi-r8-manifest.json","image":"/cars/audi-r8.webp","category":"road",illustrative:[],parts:sourceParts(["body","wheels","glass"],"https://sketchfab.com/3d-models/audi-r8-e17e438f076f4427a58d93aa779edaed",false)},
{"id":"bugatti-veyron","make":"Bugatti","name":"Veyron Super Sport","edition":"2010 · 16.4","color":"Red, black and white","paint":"#d93d32","creator":"andikapratamaw","source":"https://sketchfab.com/3d-models/bugatti-veyron-164-super-sport-lowpoly-0ee4c65face949efa4500deb17c79150","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/bugatti-veyron.glb","manifest":"/models/bugatti-veyron-manifest.json","image":"/cars/bugatti-veyron.webp","category":"road",illustrative:[],parts:sourceParts(["body","wheels","glass","cabin","drive"],"https://sketchfab.com/3d-models/bugatti-veyron-164-super-sport-lowpoly-0ee4c65face949efa4500deb17c79150",false)},
{"id":"jaguar-e-type","make":"Jaguar","name":"E-Type","edition":"1961 · Series 1","color":"Black","paint":"#16191d","creator":"Nommoc","source":"https://sketchfab.com/3d-models/jaguar-etype-32aa25ea6e1b40f395b2aff33ca0a279","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/jaguar-e-type.glb","manifest":"/models/jaguar-e-type-manifest.json","image":"/cars/jaguar-e-type.webp","category":"road",illustrative:[],parts:sourceParts(["body","wheels","glass","cabin","drive"],"https://sketchfab.com/3d-models/jaguar-etype-32aa25ea6e1b40f395b2aff33ca0a279",false)},
{"id":"mclaren-f1","make":"McLaren","name":"F1 GTR Longtail","edition":"1997 · GT1","color":"Gold and green","paint":"#c9a154","creator":"vecarz","source":"https://sketchfab.com/3d-models/a6dbc062d2e843828c392bbd07727ead","license":"CC BY-NC-SA 4.0","licenseUrl":"https://creativecommons.org/licenses/by-nc-sa/4.0/","model":"/models/mclaren-f1.glb","manifest":"/models/mclaren-f1-manifest.json","image":"/cars/mclaren-f1.webp","category":"road",illustrative:[],parts:sourceParts(["body","wheels","glass","cabin","drive"],"https://sketchfab.com/3d-models/a6dbc062d2e843828c392bbd07727ead",false)},
{"id":"rolls-royce-cullinan","make":"Rolls-Royce","name":"Cullinan","edition":"2019 · Low-poly study","color":"Red","paint":"#c24033","creator":"NewViStudios","source":"https://sketchfab.com/3d-models/rolls-royce-cullinan-61f16a1d5be2403abcdd8fa552f730f7","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/rolls-royce-cullinan.glb","manifest":"/models/rolls-royce-cullinan-manifest.json","image":"/cars/rolls-royce-cullinan.webp","category":"road",illustrative:[],parts:sourceParts(["body","wheels","cabin"],"https://sketchfab.com/3d-models/rolls-royce-cullinan-61f16a1d5be2403abcdd8fa552f730f7",false)},
{"id":"kia-forte","make":"Kia","name":"Forte","edition":"2019 · Sedan","color":"Silver","paint":"#9a9d98","creator":"teenlin3","source":"https://sketchfab.com/3d-models/kia-forte-2019-6d6b3c1ecec44756ae7868dad4e00874","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/kia-forte.glb","manifest":"/models/kia-forte-manifest.json","image":"/cars/kia-forte.webp","category":"road",illustrative:[],parts:sourceParts(["body","wheels"],"https://sketchfab.com/3d-models/kia-forte-2019-6d6b3c1ecec44756ae7868dad4e00874",false)},
{"id": "f1-sf23", "make": "Scuderia Ferrari", "name": "SF-23", "edition": "2023 \u00b7 Formula 1", "color": "Racing red", "paint": "#e13637", "creator": "Redgrund", "source": "https://sketchfab.com/3d-models/scuderia-ferrari-f1-sf23-2023-ecb0f812bc454331bbe721655b0780ec", "license": "CC BY 4.0", "licenseUrl": "https://creativecommons.org/licenses/by/4.0/", "model": "/models/f1-sf23.glb", "manifest": "/models/f1-sf23-manifest.json", "image": "/cars/f1-sf23.webp", "category": "formula-1", illustrative:[],parts:sourceParts(["wheels", "body"],"https://sketchfab.com/3d-models/scuderia-ferrari-f1-sf23-2023-ecb0f812bc454331bbe721655b0780ec",true)},
{"id": "f1-amr23", "make": "Aston Martin", "name": "AMR23", "edition": "2023 \u00b7 Formula 1", "color": "Racing green", "paint": "#167b68", "creator": "Redgrund", "source": "https://sketchfab.com/3d-models/aston-martin-f1-amr23-2023-f6ba825a43b146a9b669934a4e1fd529", "license": "CC BY 4.0", "licenseUrl": "https://creativecommons.org/licenses/by/4.0/", "model": "/models/f1-amr23.glb", "manifest": "/models/f1-amr23-manifest.json", "image": "/cars/f1-amr23.webp", "category": "formula-1", illustrative:[],parts:sourceParts(["body", "wheels"],"https://sketchfab.com/3d-models/aston-martin-f1-amr23-2023-f6ba825a43b146a9b669934a4e1fd529",true)},
{"id":"f1-mercedes-w14","make":"Mercedes-AMG","name":"W14","edition":"2023 · Formula 1","color":"Black","paint":"#141719","creator":"3dblender_1","source":"https://sketchfab.com/3d-models/mercedes-f1-w14-free-26fda66f3e8a48d5a636056f8a64e299","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/f1-mercedes-w14.glb","manifest":"/models/f1-mercedes-w14-manifest.json","image":"/cars/f1-mercedes-w14.webp","category":"formula-1",illustrative:[],parts:sourceParts(["body","wheels","cabin","suspension"],"https://sketchfab.com/3d-models/mercedes-f1-w14-free-26fda66f3e8a48d5a636056f8a64e299",true)},
{"id":"f1-mclaren-mp45","make":"McLaren-Honda","name":"MP4/5","edition":"1989 · Formula 1","color":"Red and white","paint":"#df302f","creator":"vecarz","source":"https://sketchfab.com/3d-models/mclaren-mp45-wwwvecarzcom-b0db423a98584469a73ad9b5df2ab969","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/f1-mclaren-mp45.glb","manifest":"/models/f1-mclaren-mp45-manifest.json","image":"/cars/f1-mclaren-mp45.webp","category":"formula-1",illustrative:[],parts:sourceParts(["body","wheels","cabin","suspension"],"https://sketchfab.com/3d-models/mclaren-mp45-wwwvecarzcom-b0db423a98584469a73ad9b5df2ab969",true)},
{"id":"f1-williams-fw14b","make":"Williams-Renault","name":"FW14B","edition":"1992 · Formula 1","color":"Blue, white and gold","paint":"#c89850","creator":"Dave Love SketchFab","source":"https://sketchfab.com/3d-models/none-3f5bce9286154ac38f2010ea931a9fb2","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/f1-williams-fw14b.glb","manifest":"/models/f1-williams-fw14b-manifest.json","image":"/cars/f1-williams-fw14b.webp","category":"formula-1",illustrative:[],parts:sourceParts(["body","wheels","cabin","suspension"],"https://sketchfab.com/3d-models/none-3f5bce9286154ac38f2010ea931a9fb2",true)},
{"id":"f1-ferrari-312t","make":"Scuderia Ferrari","name":"312T","edition":"1976 · Formula 1","color":"Racing red","paint":"#c8272c","creator":"Dave Love SketchFab","source":"https://sketchfab.com/3d-models/1976-ferrari-312t-b82c13cee0d24966ae66d0324ac12054","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/f1-ferrari-312t.glb","manifest":"/models/f1-ferrari-312t-manifest.json","image":"/cars/f1-ferrari-312t.webp","category":"formula-1",illustrative:[],parts:sourceParts(["body","wheels"],"https://sketchfab.com/3d-models/1976-ferrari-312t-b82c13cee0d24966ae66d0324ac12054",true)},
{"id":"f1-mclaren-mp44","make":"McLaren-Honda","name":"MP4/4","edition":"1988 · Formula 1","color":"Red and white","paint":"#e8362f","creator":"Dave Love SketchFab","source":"https://sketchfab.com/3d-models/mclaren-mp44-for-dallin-l-97d01d1d29ac45f19b161f7ff720d481","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/f1-mclaren-mp44.glb","manifest":"/models/f1-mclaren-mp44-manifest.json","image":"/cars/f1-mclaren-mp44.webp","category":"formula-1",illustrative:[],parts:sourceParts(["body","wheels","glass"],"https://sketchfab.com/3d-models/mclaren-mp44-for-dallin-l-97d01d1d29ac45f19b161f7ff720d481",true)},
{"id":"f1-lotus-49","make":"Team Lotus","name":"49","edition":"1968 · Formula 1","color":"Red, white and gold","paint":"#c8322a","creator":"dark_igorek","source":"https://sketchfab.com/3d-models/formula-1-lotus-49c-d08e707e8d4442469f3bfacd5d5d3441","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/f1-lotus-49.glb","manifest":"/models/f1-lotus-49-manifest.json","image":"/cars/f1-lotus-49.webp","category":"formula-1",illustrative:[],parts:sourceParts(["body","wheels","glass"],"https://sketchfab.com/3d-models/formula-1-lotus-49c-d08e707e8d4442469f3bfacd5d5d3441",true)},
{"id":"f1-ferrari-f310","make":"Scuderia Ferrari","name":"F310","edition":"1997 · Formula 1","color":"Racing red","paint":"#c8102e","creator":"Dave Love SketchFab","source":"https://sketchfab.com/3d-models/1997-ferrari-f310-b484d18bf1de40f5b664e30ac5e55efa","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/f1-ferrari-f310.glb","manifest":"/models/f1-ferrari-f310-manifest.json","image":"/cars/f1-ferrari-f310.webp","category":"formula-1",illustrative:[],parts:sourceParts(["body","wheels","cabin"],"https://sketchfab.com/3d-models/1997-ferrari-f310-b484d18bf1de40f5b664e30ac5e55efa",true)},
{"id":"f1-redbull-rb6","make":"Red Bull Racing","name":"RB6","edition":"2010 · Formula 1","color":"Blue, red and yellow","paint":"#0c2e6b","creator":"Dave Love SketchFab","source":"https://sketchfab.com/3d-models/2010-redbull-rb6-c826a48f888c4a0996ef9ca57e69d050","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/f1-redbull-rb6.glb","manifest":"/models/f1-redbull-rb6-manifest.json","image":"/cars/f1-redbull-rb6.webp","category":"formula-1",illustrative:[],parts:sourceParts(["body","wheels","glass"],"https://sketchfab.com/3d-models/2010-redbull-rb6-c826a48f888c4a0996ef9ca57e69d050",true)},
{"id":"f1-ferrari-f2004","make":"Scuderia Ferrari","name":"F2004","edition":"2004 · Formula 1","color":"Racing red","paint":"#c8102e","creator":"Dave Love SketchFab","source":"https://sketchfab.com/3d-models/2004-ferrari-f2004-827e64acecba4f008759ae30a5bfeecc","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/f1-ferrari-f2004.glb","manifest":"/models/f1-ferrari-f2004-manifest.json","image":"/cars/f1-ferrari-f2004.webp","category":"formula-1",illustrative:[],parts:sourceParts(["body","wheels"],"https://sketchfab.com/3d-models/2004-ferrari-f2004-827e64acecba4f008759ae30a5bfeecc",true)},
{"id":"f1-lotus-72","make":"Team Lotus","name":"72","edition":"1972 · Formula 1","color":"Black and gold","paint":"#1a1712","creator":"Dave Love SketchFab","source":"https://sketchfab.com/3d-models/1972-lotus-72d-3b1fafbc153746aebad4a245f4acdd52","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/f1-lotus-72.glb","manifest":"/models/f1-lotus-72-manifest.json","image":"/cars/f1-lotus-72.webp","category":"formula-1",illustrative:[],parts:sourceParts(["body","wheels"],"https://sketchfab.com/3d-models/1972-lotus-72d-3b1fafbc153746aebad4a245f4acdd52",true)},
{"id":"f1-brabham-bt52","make":"Brabham-BMW","name":"BT52","edition":"1983 · Formula 1","color":"White, blue and Parmalat navy","paint":"#1c2a52","creator":"Dave Love SketchFab","source":"https://sketchfab.com/3d-models/1983-brabham-bt52-fb5eb650f4584192bf7d6b25d39d3688","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/f1-brabham-bt52.glb","manifest":"/models/f1-brabham-bt52-manifest.json","image":"/cars/f1-brabham-bt52.webp","category":"formula-1",illustrative:[],parts:sourceParts(["body","wheels","cabin"],"https://sketchfab.com/3d-models/1983-brabham-bt52-fb5eb650f4584192bf7d6b25d39d3688",true)},
{"id":"f1-williams-fw07","make":"Williams-Saudia","name":"FW07","edition":"1979 · Formula 1","color":"Green, white and blue","paint":"#3c5c3c","creator":"Dave Love SketchFab","source":"https://sketchfab.com/3d-models/1979-williams-fw07-db7dece06d8b410d8ac923cff93eca28","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/f1-williams-fw07.glb","manifest":"/models/f1-williams-fw07-manifest.json","image":"/cars/f1-williams-fw07.webp","category":"formula-1",illustrative:[],parts:sourceParts(["body","wheels","cabin"],"https://sketchfab.com/3d-models/1979-williams-fw07-db7dece06d8b410d8ac923cff93eca28",true)},
{"id":"ford-mustang-gt500","make":"Shelby","name":"GT500","edition":"1967 · Cobra GT500","color":"Dark blue","paint":"#0f2a4a","creator":"Ddiaz Design","source":"https://sketchfab.com/3d-models/1967-ford-mustang-shelby-cobra-gt500-e310cc7537bf4d1aa644a2c233a5fec6","license":"CC BY-NC-SA 4.0","licenseUrl":"https://creativecommons.org/licenses/by-nc-sa/4.0/","model":"/models/ford-mustang-gt500.glb","manifest":"/models/ford-mustang-gt500-manifest.json","image":"/cars/ford-mustang-gt500.webp","category":"road",illustrative:[],parts:sourceParts(["body","wheels","glass","cabin"],"https://sketchfab.com/3d-models/1967-ford-mustang-shelby-cobra-gt500-e310cc7537bf4d1aa644a2c233a5fec6",false)},
{"id":"bmw-m3-gtr","make":"BMW","name":"M3 GTR","edition":"2001 · ALMS race car","color":"Advan red and black","paint":"#c8272c","creator":"Dave Love SketchFab","source":"https://sketchfab.com/3d-models/bmw-m3-gtr-26ca15169b704081861cb402c382b388","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/bmw-m3-gtr.glb","manifest":"/models/bmw-m3-gtr-manifest.json","image":"/cars/bmw-m3-gtr.webp","category":"road",illustrative:[],parts:sourceParts(["body","wheels","glass"],"https://sketchfab.com/3d-models/bmw-m3-gtr-26ca15169b704081861cb402c382b388",false)},
{"id":"mclaren-f1-1993","make":"McLaren","name":"F1","edition":"1993 · Road car","color":"Silver","paint":"#c7c9ca","creator":"Alex.Ka.","source":"https://sketchfab.com/3d-models/mclaren-f1-1993-by-alexka-294df724d96241cdbe0e0f3c91ad7fce","license":"CC BY-NC 4.0","licenseUrl":"https://creativecommons.org/licenses/by-nc/4.0/","model":"/models/mclaren-f1-1993.glb","manifest":"/models/mclaren-f1-1993-manifest.json","image":"/cars/mclaren-f1-1993.webp","category":"road",illustrative:[],parts:sourceParts(["body","wheels","cabin","drive"],"https://sketchfab.com/3d-models/mclaren-f1-1993-by-alexka-294df724d96241cdbe0e0f3c91ad7fce",false)},
{"id":"f1-mclaren-mcl39","make":"McLaren","name":"MCL39","edition":"2025 · Formula 1","color":"Papaya orange and black","paint":"#e8620c","creator":"Abu Saif","source":"https://sketchfab.com/3d-models/2025-mclaren-mcl39-710fc591067848d0b3068ae3fb160ede","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/f1-mclaren-mcl39.glb","manifest":"/models/f1-mclaren-mcl39-manifest.json","image":"/cars/f1-mclaren-mcl39.webp","category":"formula-1",illustrative:[],parts:sourceParts(["body","wheels","glass"],"https://sketchfab.com/3d-models/2025-mclaren-mcl39-710fc591067848d0b3068ae3fb160ede",true)},
{"id":"f1-ferrari-sf25","make":"Scuderia Ferrari","name":"SF-25","edition":"2025 · Formula 1","color":"Racing red","paint":"#c8102e","creator":"Abu Saif","source":"https://sketchfab.com/3d-models/ferrari-sf-25-11b53fd8dc324ab7b7fed6b43c62e398","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/f1-ferrari-sf25.glb","manifest":"/models/f1-ferrari-sf25-manifest.json","image":"/cars/f1-ferrari-sf25.webp","category":"formula-1",illustrative:[],parts:sourceParts(["body","wheels"],"https://sketchfab.com/3d-models/ferrari-sf-25-11b53fd8dc324ab7b7fed6b43c62e398",true)},
{"id":"f1-redbull-rb21","make":"Red Bull Racing","name":"RB21","edition":"2025 · Formula 1","color":"Navy and gold","paint":"#0c1a3c","creator":"Abu Saif","source":"https://sketchfab.com/3d-models/f1-2025-redbull-rb21-418c3b3cdf9d41ea8beb15076d875a86","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/f1-redbull-rb21.glb","manifest":"/models/f1-redbull-rb21-manifest.json","image":"/cars/f1-redbull-rb21.webp","category":"formula-1",illustrative:[],parts:sourceParts(["body","wheels","glass"],"https://sketchfab.com/3d-models/f1-2025-redbull-rb21-418c3b3cdf9d41ea8beb15076d875a86",true)},
{"id":"f1-mercedes-w15","make":"Mercedes-AMG Petronas","name":"W15","edition":"2024 · Formula 1","color":"Black and Petronas turquoise","paint":"#0c0c0e","creator":"Abu Saif","source":"https://sketchfab.com/3d-models/mercedes-w15-0c6b95f5329f4a4e8c3f039d890ee193","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","model":"/models/f1-mercedes-w15.glb","manifest":"/models/f1-mercedes-w15-manifest.json","image":"/cars/f1-mercedes-w15.webp","category":"formula-1",illustrative:[],parts:sourceParts(["body","wheels","glass","cabin"],"https://sketchfab.com/3d-models/mercedes-w15-0c6b95f5329f4a4e8c3f039d890ee193",true)},
{"id":"aston-martin-one77","make":"Aston Martin","name":"One-77","edition":"2009 · Limited hypercar","color":"Silver","paint":"#8f99a3","creator":"Ddiaz Design","source":"https://sketchfab.com/3d-models/2009-aston-martin-one-77-bc691ea66a2747aca226fbf3c51fbb04","license":"CC BY-NC-SA 4.0","licenseUrl":"https://creativecommons.org/licenses/by-nc-sa/4.0/","model":"/models/aston-martin-one77.glb","manifest":"/models/aston-martin-one77-manifest.json","image":"/cars/aston-martin-one77.webp","category":"road",illustrative:[],parts:sourceParts(["body","wheels","glass","cabin","drive"],"https://sketchfab.com/3d-models/2009-aston-martin-one-77-bc691ea66a2747aca226fbf3c51fbb04",false)},
{id:'model-x',make:'Tesla',name:'Model X',edition:'Electric · Pre-refresh',color:'Steel blue',paint:'#8aa6bd',model:'/models/model-x.glb',manifest:'/models/model-x-manifest.json',image:'/cars/model-x.webp',creator:'cgi Moon',source:'https://www.blendkit.com/asset-gallery-detail/983e8f94-5a56-44a4-94d9-eed5e4cdcd6c/',license:'Blendkit Royalty Free',licenseUrl:'https://www.blendkit.com/docs/licenses/',parts:teslaParts,illustrative:['battery','drive','suspension']}
);
